### ISSUE TITLE
The master version is not deployed

### ISSUE THREAD

**Issue by cristianbote** [paulirish/mojibar-web#3]
Just FYI the version from master is not deployed. Spent a few minutes on that long frame, just to realise @developit already took care of it 😄... in master.

![Screenshot 2019-10-22 at 09 32 11](https://user-images.githubusercontent.com/3405161/67262837-dc5bc780-f4ae-11e9-8cc5-2d4702b63de7.png)

**Comment by paulirish** [comment]
ha. :) 

yah thanks for taking a look.

updated.
